## Singular Value Decomposition
- used in linear algebra
- decompose a matrix
  
SVD of a matrix A (of size m x n) is represented as: $ A=UΣV^T $
- $ U $ - m x m orthogonal matrix whose columns are the left singular vectors of A
- $ Σ $ - m x n matrix containing the singular values of A in descending order
- $ V^T $ - transpose of an n x n orthogonal matrix, where the columns are the right singular vectors of A

### Steps:
1. Calculate $ AA^T $
2. Calculate Eigen values of $ AA^T $
    - det($ AA^T - \lambda I $) = 0
3. Find Right Singular Vectors [Eigen Vectors of $ A^TA $ = $ V^T $]
    - for all $ \lambda : (A^TA-\lambda I)v = 0 $ 
4. Compute Left Singular Vectors [Eigen Vectors of $ AA^T $ = Matrix U]
    - $ u_i = (1/\sigma _i) * A * v_i $
5. Find SVD of A as: $ A=UΣV^T $

In [22]:
import numpy as np
from scipy.linalg import svd
from sklearn.decomposition import TruncatedSVD

In [23]:
A = np.array([[3,2,2], [2,3,-2]])

In [24]:
U, singular, V_transpose = svd(A)
print("U = \n", U)
print("\nsingular = \n", singular)
print("\nV_transpose = \n", V_transpose)

U = 
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

singular = 
 [5. 3.]

V_transpose = 
 [[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


### Truncated Singular Value Decomposition (Truncated SVD)
- dimensionality reduction technique
- similar purpose to PCA

In [26]:
svd = TruncatedSVD(n_components=1)
A_transformed = svd.fit_transform(A)
print("Transformed Matrix:")
print(A_transformed)

Transformed Matrix:
[[3.53553391]
 [3.53553391]]


### Applications:
- data comperssion
- noise removal
- reccomendation systems
- image analysis