## Singular Value Decomposition
- used in linear algebra
- decompose a matrix to its core components
- dimensionality reduction
- express our original matrix as a linear combination of low-rank matrices
- works better with sparse data
  
SVD of a matrix A (of size m x n) is represented as: $ A=UΣV^T $
- $ U $ - m x m orthogonal matrix whose columns are the left singular vectors of A
- $ Σ $ - m x n matrix containing the singular values of A in descending order
- $ V^T $ - transpose of an n x n orthogonal matrix, where the columns are the right singular vectors of A

### Steps:
1. Calculate $ AA^T $
2. Calculate Eigen values of $ AA^T $
    - det($ AA^T - \lambda I $) = 0
3. Find Right Singular Vectors [Eigen Vectors of $ A^TA $ = $ V^T $]
    - for all $ \lambda : (A^TA-\lambda I)v = 0 $ 
4. Compute Left Singular Vectors [Eigen Vectors of $ AA^T $ = Matrix U]
    - $ u_i = (1/\sigma _i) * A * v_i $
5. Find SVD of A as: $ A=UΣV^T $

In [59]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

In [60]:
A = np.array([[3,2,2], [2,3,-2]])

In [61]:
U, singular, V_transpose = np.linalg.svd(A)
print("U = \n", U)
print("\nsingular = \n", singular)
print("\nV_transpose = \n", V_transpose)

U = 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

singular = 
 [5. 3.]

V_transpose = 
 [[ 7.07106781e-01  7.07106781e-01  3.67439059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


In [ ]:
# Make sure singular values are in a diagonal matrix of the correct shape
d = np.diag(singular)

# The diagonal matrix Sigma should have shape (2, 3), so we need to pad it with zeros
s = np.zeros((U.shape[1], V_transpose.shape[0]))
s[:d.shape[0], :d.shape[1]] = d
print(s)
print()

A_remake = (U @ s @ V_transpose)
print(A_remake)

[[5. 0. 0.]
 [0. 3. 0.]]

[[ 3.  2.  2.]
 [ 2.  3. -2.]]


### Truncated Singular Value Decomposition (Truncated SVD)
- dimensionality reduction technique
- similar purpose to PCA
- produce matrices with the specified number of columns

In [63]:
svd = TruncatedSVD(n_components=2)
A_transformed = svd.fit_transform(A)
print("Transformed Matrix:")
print(A_transformed)

Transformed Matrix:
[[ 3.53553391  2.12132034]
 [ 3.53553391 -2.12132034]]


### Applications:
- data comperssion
- noise removal
- reccomendation systems
- image analysis