## NumPy
- multi dimensional array library

- less bytes of memory required
    for a list of int:
    - list: each int is represented with: size, ref count, object type, object value (4 bytes, 8 bytes x 3)
    - numpy: 4 bytes default, can specify number of bytes
- no typechecking while iterating
- contiguous memory
    - simd vector processing
        - single instruction multiple data
    - effective cache utilization

In [34]:
import numpy as np

In [35]:
a = [1,2,3,4]
b = [5,6,7,8] 

an = np.array(a)
bn = np.array(b)

print(a+b)
print(an+bn)

[1, 2, 3, 4, 5, 6, 7, 8]
[ 6  8 10 12]


In [36]:
cn = np.array([[1,2,3,4,5,6,7,8],[5,6,7,8,9,10,11,12]])

print(cn.ndim)
print(cn.shape)
print(cn.size)
print(cn.dtype)

2
(2, 8)
16
int64


In [37]:
# start : end (exclusive) : stepsize
cn[1,1:9:2]

array([ 6,  8, 10, 12])

In [38]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [41]:
np.full_like(a, 2)

array([2, 2, 2, 2])

In [42]:
np.random.rand(3, 4, 2)

array([[[0.75223256, 0.36949833],
        [0.49837298, 0.69760707],
        [0.40388833, 0.61649397],
        [0.66296049, 0.97933422]],

       [[0.99834632, 0.62343515],
        [0.19732608, 0.43046526],
        [0.70280739, 0.68028923],
        [0.53386185, 0.50399931]],

       [[0.14542505, 0.80049948],
        [0.51316292, 0.47687373],
        [0.48028977, 0.16557046],
        [0.49200074, 0.97370512]]])

In [43]:
np.random.random_sample(an.shape)

array([0.30807746, 0.77509311, 0.82763145, 0.54272063])

In [44]:
np.random.randint(4, 11, size=(3, 4))


array([[ 7,  4,  5,  6],
       [ 4,  6,  6,  9],
       [10,  7,  5,  6]], dtype=int32)

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
a = np.ones((5, 5))
print(a)
z = np.zeros((3, 3))
z[1,1] = 4
print(z)
a[1:4,1:4] = z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 4. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a + 1

array([[2., 2., 2., 2., 2.],
       [2., 1., 1., 1., 2.],
       [2., 1., 5., 1., 2.],
       [2., 1., 1., 1., 2.],
       [2., 2., 2., 2., 2.]])

: 