## NumPy
- multi dimensional array library

- less bytes of memory required
    for a list of int:
    - list: each int is represented with: size, ref count, object type, object value (4 bytes, 8 bytes x 3)
    - numpy: 4 bytes default, can specify number of bytes
- no typechecking while iterating
- contiguous memory
    - simd vector processing
        - single instruction multiple data
    - effective cache utilization

In [80]:
import numpy as np

In [81]:
a = [1,2,3,4]
b = [5,6,7,8] 

an = np.array(a)
bn = np.array(b)

print(a+b)
print(an+bn)

[1, 2, 3, 4, 5, 6, 7, 8]
[ 6  8 10 12]


In [82]:
cn = np.array([[1,2,3,4,5,6,7,8],[5,6,7,8,9,10,11,12]])

print(cn.ndim)
print(cn.shape)
print(cn.size)
print(cn.dtype)

2
(2, 8)
16
int64


In [87]:
# start : end (exclusive) : stepsize
cn[1,1:9:2]

array([ 6,  8, 10, 12])

In [88]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [90]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [91]:
np.full_like(a, 2)

array([2, 2, 2, 2])

In [101]:
np.random.rand(3, 4, 2)

array([[[0.63775892, 0.291376  ],
        [0.96632293, 0.02570043],
        [0.0940186 , 0.03972803],
        [0.40192924, 0.40722167]],

       [[0.3509179 , 0.18004488],
        [0.89784836, 0.07478029],
        [0.31191439, 0.09034686],
        [0.42042644, 0.63982373]],

       [[0.26523335, 0.65900047],
        [0.21306543, 0.76960255],
        [0.34783852, 0.07458068],
        [0.25836054, 0.31352828]]])